spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orm
    password: "@Ongod123"
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: LMS

server:
  port: 8084